### PR TITLE
add some new operator's code and small adjustment

### PR DESCRIPTION
**Pull request by adifdwimaulana**
I've add some new operator's code. And maybe for the next development we could add information about provider in other countries so we need to change the array object structure. For now, I only add a few operators and small adjustment

### CODE REVIEW

**Comment by rfnajid** [comment]
Adding other countries' phone number is really nice idea. I haven't thought about it before. My focus was on Indonesian numbers only, including landline phone number. As you say, to provide future development, we need to restructure the data for global use.

Thanks for adding some new operators. But before i accept  your pull request, i will be glad if you add unit test for new operators.

How to add unit test is very simple. 
1. Open \_\_test\_\_/getOperator.spec.js
2. Add new test scenarios to new operators
3. run "npm test"
4. It must pass all of the test scenarios

**Comment by adifdwimaulana** [comment]
I've add unit test to the newest commit and all the test passed. And I delete one of your previous operator "LOOP", because I followed the newest code number based on each provider and change it to simPATI

**Comment by rfnajid** [comment]
Nice job!

Regarding "LOOP", I think we should separete LOOP and simPATI, because it's entirely different product. 
https://www.telkomsel.com/en/loop
https://www.telkomsel.com/en/simpati

Even LOOP has its own website, https://www.loop.co.id/

But, people are having misunderstanding, they always think that LOOP and simPATI are the same thing, sometimes they call it simPATI LOOP. 

Don't worry i'll merge and restore your "LOOP" changes by myself.

**Comment by rfnajid** [comment]
I merged "Ceria" to Net1, because Ceria rebranded to Net1 (https://id.wikipedia.org/wiki/Net1_Indonesia) and Mobile-8 merged to Smartfren because Mobile-8 rebranded to Smartfren (https://bisnis.tempo.co/read/322393/akuisisi-smart-telecom-mobile-8-berganti-nama)

Thanks for your contribution, your change successfully published to [npmjs](https://www.npmjs.com/package/no-telp)

**Pull request merged**
